config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'
  get 'pages/show'

  resources :books, only: [:index, :new, :create, :show]
  
  get 'home/welcome'

  get 'users/my',      to: "users#show", as: :user
  get 'users/my/edit', to: "users#edit", as: :edit_user
  put 'users/my',      to: "users#update", as: :update_user
  resources :reviews
  root to: 'home#index'
  
end

app/models/book.rb
class Book < ApplicationRecord

  has_many :users, through: :user_books
  has_many :user_books
  
  # データ検証(入力に制限をかけるなど)：validation
  validates :title, :author, presence: true # presence：必須
  validates :title, :author, :publisher, length: { maximum: 100} # length {}：文字数制限
  validates :title, uniqueness: true
  validate :validates_past_published_date # 独自にデータ検証かける場合はvalidatesではなくvalidate 

  # validates :title, presence: true, length: { maximum: 100 }, uniqueness: true
  
  private
  
  def validates_past_published_date
    if self.published_date.present?
      if Time.zone.today < self.published_date
        self.errors.add :published_date, :invalid
      end
    end
  end

end

app/controllers/books_controller.rb
# -*- coding: utf-8 -*-
class BooksController < ApplicationController
  def index
    if params[:search]
      @books = Book.where(title: params[:search])
    end
  end
  
  def show
    @book    = Book.find(params[:id])
    @reviews = Review.where(book_id: params[:id]).all
    @books   = Book.all
  end

  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
     
    if @book.save
                  # "/books , ページに「本の保存に～」を表示"
      redirect_to books_path, notice: '本の保存に成功しました。'
    else
      # 入力した情報を残したままもう一度入力させる画面を表示
      render action: :new
    end
  end
   
  private
   
  def book_params
    params.require(:book).permit(:title, :author, :published_date, :publisher)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<h1>本検索</h1>
<%= form_tag(books_path, method: :get) do %>
<%= text_field_tag :search %>
<%= submit_tag 'Search', :name => nil %>
<% end %>

<% if params[:search].present? %>
<%   if @books.present? %>
<%     @books.each do |book| %>
<%= book.title %>
<%     end %>
<%   else %>
<h3>検索結果がありません</h3>
<%   end %>
<% end %>

app/views/books/new.html.erb
<% if @book.errors.any? 
     # エラーがあるかを確認し、あった場合表示
%>
  <div id="error_explanation">
   <ul>
    <% @book.errors.full_messages.each do |message| %>
    <% 1 # @book.errors.full_messagesでerrorに対するmsg配列を取得 %>
    <% 1 # eachを用いてerror msgを１つずつ表示 %>
    <li>
     <%= message %>
    </li>
    <% end %>
   </ul>
   </div>
<% end %>

<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title 
        # テキスト：text_field
  %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :published_date %>  
  <%= f.date_field :published_date
      # 日付：date_field
  %>
  <%= f.label :publisher %> 
  <%= f.text_field :publisher %>
  <%= f.submit
        # 登録するボタン
  %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %>グループ詳細</h1>
<%= @book.title%>
<%= @book.author%>
<%= @book.publisher%>
<h2>レビュー一覧</h2>
<% @reviews.each do |review|%>
  <%= link_to review.title, review%>
  <br>
<% end %>
<br>
<%= link_to "新しいレビューを投稿する", new_review_path%>